services:
  database:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: airsoft_db
    ports:
      - "5433:5432"
